name: Dart

on:
  push:
    branches: [ 'develop', 'linter_setup' ]
  pull_request:
    branches: [ 'main', 'develop' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: 'stable'
      - run: flutter --version
      - run: cd /home/runner/work/ReusEdAppG7/ReusEdAppG7/reused_flutter

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos
